name: bible_seek
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter

  provider: ^6.0.0
  html: ^0.15.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  json_annotation: ^4.8.0
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  google_fonts: ^8.0.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^3.2.3
  json_serializable: ^6.3.0
  mockito: ^5.0.0
  riverpod_generator:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/googleSymbol.png
    - assets/images/facebookSymbol.png
  uses-material-design: true

flutter_native_splash:
  color: "#A59F8C"
  image: assets/images/bibleseek_logo.png
  android: true
  ios: true